name: Repository Dispatch - New Imm0
# permissions:
# contents: write
on:
  repository_dispatch:
    types: [new-immo]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the event
        env:
          EVENT: ${{ toJson(github.event) }}
        run: |
          printf "######## raw\n"
          printf "${{ github.event }}"
          printf "######## json\n"
          printf "$EVENT\n"
          printf "######## json/echo\n"
          echo "$EVENT"
          printf "########\n"

      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Fetch and Extract
        run: |
          url=$(printf "$EVENT" | sed -n '/^https:/s/"//p')
          printf "url: $url\n"
          ./bin/extract $url

      - name: Convert
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: ./bin/store

      - name: Debug
        run: |
          pwd
          ls -al
          find .
          env
